# Generated by Django 5.2.7 on 2025-10-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='newone',
        ),
    ]
